### ISSUE TITLE
数据库集合不存在

### ISSUE THREAD

**Issue by ghost** [skymxc/booklist#1]
我想问一下，我在运行这个源代码的时候它报错说数据库集合不存在，然后只能运行到授权那里，我具体的APPID还有env环境都改了，问题是在哪里（小白一个，本来打算变看代码边学小程序，但运行又出现问题，用的是云开发）

**Comment by skymxc** [comment]
> 我想问一下，我在运行这个源代码的时候它报错说数据库集合不存在，然后只能运行到授权那里，我具体的APPID还有env环境都改了，问题是在哪里（小白一个，本来打算变看代码边学小程序，但运行又出现问题，用的是云开发）

你在云开发数据库里把这几个集合建一下，我也是学习练手的项目，现在小程序的 API 更新很快，里面的很多API可能现在有更好的，有什么问题再交流把。
![数据库集合](https://raw.githubusercontent.com/skymxc/booklist/master/picture/数据集合.png)
